name: test project
on: [push, pull_request]
jobs:
    build-test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
              node-version: [8.x, 10.x, 12.x]

        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: npm install
            - name: Transpile the lib
              run: npm run build
            - name: Test the lib
              run: npm test
